id = "sakurae"
name = "SakuraE"
version = "0.1.2"
schema_version = 1
authors = ["FZSGBall"]
description = "SakuraE language support for Zed."
repository = "https://github.com/PowerAngelXD/SakuraE"
languages = ["languages/sakurae"]

[grammars.sakurae]
repository = "https://github.com/PowerAngelXD/SakuraE"
rev = "698b331"
path = "sakurae-tree-sitter"

[language_servers.sakurae-language-server]
language = "SakuraE"
languages = []
